# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolSet(object):
    def setupUi(self, ToolSet):
        ToolSet.setObjectName("ToolSet")
        ToolSet.resize(1295, 832)
        self.centralwidget = QtWidgets.QWidget(ToolSet)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 128, 564))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.tool_cfg = QtWidgets.QToolBox(self.scrollAreaWidgetContents_2)
        self.tool_cfg.setGeometry(QtCore.QRect(0, 50, 131, 151))
        self.tool_cfg.setObjectName("tool_cfg")
        self.serial_cfg = QtWidgets.QWidget()
        self.serial_cfg.setGeometry(QtCore.QRect(0, 0, 131, 99))
        self.serial_cfg.setObjectName("serial_cfg")
        self.b_open = QtWidgets.QPushButton(self.serial_cfg)
        self.b_open.setGeometry(QtCore.QRect(50, 60, 75, 23))
        self.b_open.setObjectName("b_open")
        self.label_2 = QtWidgets.QLabel(self.serial_cfg)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 54, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.serial_cfg)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 54, 22))
        self.label_3.setObjectName("label_3")
        self.serial_port = QtWidgets.QComboBox(self.serial_cfg)
        self.serial_port.setGeometry(QtCore.QRect(50, 0, 69, 22))
        self.serial_port.setObjectName("serial_port")
        self.baudrate = QtWidgets.QComboBox(self.serial_cfg)
        self.baudrate.setGeometry(QtCore.QRect(50, 30, 69, 22))
        self.baudrate.setObjectName("baudrate")
        self.tool_cfg.addItem(self.serial_cfg, "")
        self.tcp_cfg = QtWidgets.QWidget()
        self.tcp_cfg.setGeometry(QtCore.QRect(0, 0, 131, 99))
        self.tcp_cfg.setObjectName("tcp_cfg")
        self.label_5 = QtWidgets.QLabel(self.tcp_cfg)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.tcp_cfg)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 54, 20))
        self.label_4.setObjectName("label_4")
        self.e_tcp_port = QtWidgets.QLineEdit(self.tcp_cfg)
        self.e_tcp_port.setGeometry(QtCore.QRect(40, 30, 81, 20))
        self.e_tcp_port.setObjectName("e_tcp_port")
        self.b_connect = QtWidgets.QPushButton(self.tcp_cfg)
        self.b_connect.setGeometry(QtCore.QRect(50, 60, 75, 23))
        self.b_connect.setObjectName("b_connect")
        self.e_ipaddr = QtWidgets.QLineEdit(self.tcp_cfg)
        self.e_ipaddr.setGeometry(QtCore.QRect(40, 0, 81, 20))
        self.e_ipaddr.setObjectName("e_ipaddr")
        self.tool_cfg.addItem(self.tcp_cfg, "")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setGeometry(QtCore.QRect(0, 300, 131, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.b_status_control = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.b_status_control.setGeometry(QtCore.QRect(10, 20, 111, 23))
        self.b_status_control.setObjectName("b_status_control")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.mode_manage = QtWidgets.QTabWidget(self.frame_4)
        self.mode_manage.setObjectName("mode_manage")
        self.tab_serial = QtWidgets.QWidget()
        self.tab_serial.setObjectName("tab_serial")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_serial)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.e_recv = QtWidgets.QTextEdit(self.tab_serial)
        self.e_recv.setObjectName("e_recv")
        self.verticalLayout_5.addWidget(self.e_recv)
        self.frame_3 = QtWidgets.QFrame(self.tab_serial)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setMinimumSize(QtCore.QSize(0, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lcd_recv_len = QtWidgets.QLCDNumber(self.frame_3)
        self.lcd_recv_len.setMinimumSize(QtCore.QSize(0, 20))
        self.lcd_recv_len.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lcd_recv_len.setDigitCount(10)
        self.lcd_recv_len.setObjectName("lcd_recv_len")
        self.horizontalLayout_6.addWidget(self.lcd_recv_len)
        self.b_clean_recv = QtWidgets.QPushButton(self.frame_3)
        self.b_clean_recv.setMinimumSize(QtCore.QSize(0, 20))
        self.b_clean_recv.setMaximumSize(QtCore.QSize(40, 16777215))
        self.b_clean_recv.setObjectName("b_clean_recv")
        self.horizontalLayout_6.addWidget(self.b_clean_recv)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setMinimumSize(QtCore.QSize(0, 20))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(25, 20))
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.c_font_size = QtWidgets.QSpinBox(self.frame_3)
        self.c_font_size.setMinimumSize(QtCore.QSize(20, 20))
        self.c_font_size.setMaximumSize(QtCore.QSize(40, 16777215))
        self.c_font_size.setObjectName("c_font_size")
        self.horizontalLayout_6.addWidget(self.c_font_size)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setMinimumSize(QtCore.QSize(0, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.c_display_font = QtWidgets.QFontComboBox(self.frame_3)
        self.c_display_font.setMinimumSize(QtCore.QSize(0, 20))
        self.c_display_font.setMaximumSize(QtCore.QSize(50, 40))
        self.c_display_font.setObjectName("c_display_font")
        self.horizontalLayout_6.addWidget(self.c_display_font)
        self.line_4 = QtWidgets.QFrame(self.frame_3)
        self.line_4.setMinimumSize(QtCore.QSize(0, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.c_hex_show = QtWidgets.QCheckBox(self.frame_3)
        self.c_hex_show.setMinimumSize(QtCore.QSize(0, 20))
        self.c_hex_show.setMaximumSize(QtCore.QSize(100, 40))
        self.c_hex_show.setObjectName("c_hex_show")
        self.horizontalLayout_6.addWidget(self.c_hex_show)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.mode_manage.addTab(self.tab_serial, "")
        self.wearform = QtWidgets.QWidget()
        self.wearform.setObjectName("wearform")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wearform)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.wearform)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.r_graphic_chn = QtWidgets.QScrollArea(self.groupBox_5)
        self.r_graphic_chn.setMinimumSize(QtCore.QSize(100, 0))
        self.r_graphic_chn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.r_graphic_chn.setWidgetResizable(True)
        self.r_graphic_chn.setObjectName("r_graphic_chn")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 98, 501))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.r_graphic_chn.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.r_graphic_chn)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.graphicsView = PlotWidget(self.frame_2)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 8)
        self.horizontalLayout.addWidget(self.frame_2)
        self.mode_manage.addTab(self.wearform, "")
        self.horizontalLayout_8.addWidget(self.mode_manage)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_3.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea_5.setTabletTracking(False)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 198, 548))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.e_extend_send_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_1.setGeometry(QtCore.QRect(40, 10, 101, 20))
        self.e_extend_send_1.setObjectName("e_extend_send_1")
        self.c_extend_send_1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_1.setGeometry(QtCore.QRect(150, 10, 71, 20))
        self.c_extend_send_1.setObjectName("c_extend_send_1")
        self.c_extend_cyclic_send = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_cyclic_send.setGeometry(QtCore.QRect(10, 490, 71, 16))
        self.c_extend_cyclic_send.setObjectName("c_extend_cyclic_send")
        self.c_entend_enter = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_entend_enter.setGeometry(QtCore.QRect(90, 490, 71, 16))
        self.c_entend_enter.setObjectName("c_entend_enter")
        self.b_extend_send_all = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_all.setGeometry(QtCore.QRect(20, 520, 131, 23))
        self.b_extend_send_all.setObjectName("b_extend_send_all")
        self.c_all_exend_send = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_all_exend_send.setGeometry(QtCore.QRect(10, 460, 71, 16))
        self.c_all_exend_send.setObjectName("c_all_exend_send")
        self.b_extend_send_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_1.setGeometry(QtCore.QRect(0, 10, 41, 20))
        self.b_extend_send_1.setObjectName("b_extend_send_1")
        self.e_extend_send_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_2.setGeometry(QtCore.QRect(40, 30, 101, 20))
        self.e_extend_send_2.setObjectName("e_extend_send_2")
        self.c_extend_send_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_2.setGeometry(QtCore.QRect(150, 30, 71, 20))
        self.c_extend_send_2.setObjectName("c_extend_send_2")
        self.b_extend_send_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_2.setGeometry(QtCore.QRect(0, 30, 41, 20))
        self.b_extend_send_2.setObjectName("b_extend_send_2")
        self.c_extend_send_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_3.setGeometry(QtCore.QRect(150, 50, 71, 20))
        self.c_extend_send_3.setObjectName("c_extend_send_3")
        self.b_extend_send_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_3.setGeometry(QtCore.QRect(0, 50, 41, 20))
        self.b_extend_send_3.setObjectName("b_extend_send_3")
        self.e_extend_send_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_3.setGeometry(QtCore.QRect(40, 50, 101, 20))
        self.e_extend_send_3.setObjectName("e_extend_send_3")
        self.c_extend_send_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_4.setGeometry(QtCore.QRect(150, 70, 71, 20))
        self.c_extend_send_4.setObjectName("c_extend_send_4")
        self.b_extend_send_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_4.setGeometry(QtCore.QRect(0, 70, 41, 20))
        self.b_extend_send_4.setObjectName("b_extend_send_4")
        self.e_extend_send_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_4.setGeometry(QtCore.QRect(40, 70, 101, 20))
        self.e_extend_send_4.setObjectName("e_extend_send_4")
        self.c_extend_send_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_5.setGeometry(QtCore.QRect(150, 90, 71, 20))
        self.c_extend_send_5.setObjectName("c_extend_send_5")
        self.b_extend_send_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_5.setGeometry(QtCore.QRect(0, 90, 41, 20))
        self.b_extend_send_5.setObjectName("b_extend_send_5")
        self.e_extend_send_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_5.setGeometry(QtCore.QRect(40, 90, 101, 20))
        self.e_extend_send_5.setObjectName("e_extend_send_5")
        self.c_extend_send_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_6.setGeometry(QtCore.QRect(150, 110, 71, 20))
        self.c_extend_send_6.setObjectName("c_extend_send_6")
        self.b_extend_send_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_6.setGeometry(QtCore.QRect(0, 110, 41, 20))
        self.b_extend_send_6.setObjectName("b_extend_send_6")
        self.e_extend_send_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_6.setGeometry(QtCore.QRect(40, 110, 101, 20))
        self.e_extend_send_6.setObjectName("e_extend_send_6")
        self.b_extend_send_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_7.setGeometry(QtCore.QRect(0, 130, 41, 20))
        self.b_extend_send_7.setObjectName("b_extend_send_7")
        self.e_extend_send_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_7.setGeometry(QtCore.QRect(40, 130, 101, 20))
        self.e_extend_send_7.setObjectName("e_extend_send_7")
        self.c_extend_send_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_7.setGeometry(QtCore.QRect(150, 130, 71, 20))
        self.c_extend_send_7.setObjectName("c_extend_send_7")
        self.b_extend_send_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_8.setGeometry(QtCore.QRect(0, 150, 41, 20))
        self.b_extend_send_8.setObjectName("b_extend_send_8")
        self.e_extend_send_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_8.setGeometry(QtCore.QRect(40, 150, 101, 20))
        self.e_extend_send_8.setObjectName("e_extend_send_8")
        self.c_extend_send_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_8.setGeometry(QtCore.QRect(150, 150, 71, 20))
        self.c_extend_send_8.setObjectName("c_extend_send_8")
        self.b_extend_send_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_9.setGeometry(QtCore.QRect(0, 170, 41, 20))
        self.b_extend_send_9.setObjectName("b_extend_send_9")
        self.e_extend_send_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_9.setGeometry(QtCore.QRect(40, 170, 101, 20))
        self.e_extend_send_9.setObjectName("e_extend_send_9")
        self.c_extend_send_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_9.setGeometry(QtCore.QRect(150, 170, 71, 20))
        self.c_extend_send_9.setObjectName("c_extend_send_9")
        self.b_extend_send_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_10.setGeometry(QtCore.QRect(0, 190, 41, 20))
        self.b_extend_send_10.setObjectName("b_extend_send_10")
        self.e_extend_send_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_10.setGeometry(QtCore.QRect(40, 190, 101, 20))
        self.e_extend_send_10.setObjectName("e_extend_send_10")
        self.c_extend_send_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_10.setGeometry(QtCore.QRect(150, 190, 71, 20))
        self.c_extend_send_10.setObjectName("c_extend_send_10")
        self.b_extend_send_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_11.setGeometry(QtCore.QRect(0, 210, 41, 20))
        self.b_extend_send_11.setObjectName("b_extend_send_11")
        self.e_extend_send_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_11.setGeometry(QtCore.QRect(40, 210, 101, 20))
        self.e_extend_send_11.setObjectName("e_extend_send_11")
        self.c_extend_send_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_11.setGeometry(QtCore.QRect(150, 210, 71, 20))
        self.c_extend_send_11.setObjectName("c_extend_send_11")
        self.b_extend_send_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_12.setGeometry(QtCore.QRect(0, 230, 41, 20))
        self.b_extend_send_12.setObjectName("b_extend_send_12")
        self.e_extend_send_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_12.setGeometry(QtCore.QRect(40, 230, 101, 20))
        self.e_extend_send_12.setObjectName("e_extend_send_12")
        self.c_extend_send_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_12.setGeometry(QtCore.QRect(150, 230, 71, 20))
        self.c_extend_send_12.setObjectName("c_extend_send_12")
        self.b_extend_send_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_13.setGeometry(QtCore.QRect(0, 250, 41, 20))
        self.b_extend_send_13.setObjectName("b_extend_send_13")
        self.e_extend_send_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_13.setGeometry(QtCore.QRect(40, 250, 101, 20))
        self.e_extend_send_13.setObjectName("e_extend_send_13")
        self.c_extend_send_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_13.setGeometry(QtCore.QRect(150, 250, 71, 20))
        self.c_extend_send_13.setObjectName("c_extend_send_13")
        self.b_extend_send_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_14.setGeometry(QtCore.QRect(0, 270, 41, 20))
        self.b_extend_send_14.setObjectName("b_extend_send_14")
        self.e_extend_send_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_14.setGeometry(QtCore.QRect(40, 270, 101, 20))
        self.e_extend_send_14.setObjectName("e_extend_send_14")
        self.c_extend_send_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_14.setGeometry(QtCore.QRect(150, 270, 71, 20))
        self.c_extend_send_14.setObjectName("c_extend_send_14")
        self.b_extend_send_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_15.setGeometry(QtCore.QRect(0, 290, 41, 20))
        self.b_extend_send_15.setObjectName("b_extend_send_15")
        self.e_extend_send_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_15.setGeometry(QtCore.QRect(40, 290, 101, 20))
        self.e_extend_send_15.setObjectName("e_extend_send_15")
        self.c_extend_send_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_15.setGeometry(QtCore.QRect(150, 290, 71, 20))
        self.c_extend_send_15.setObjectName("c_extend_send_15")
        self.b_extend_send_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_16.setGeometry(QtCore.QRect(0, 310, 41, 20))
        self.b_extend_send_16.setObjectName("b_extend_send_16")
        self.e_extend_send_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_16.setGeometry(QtCore.QRect(40, 310, 101, 20))
        self.e_extend_send_16.setObjectName("e_extend_send_16")
        self.c_extend_send_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_16.setGeometry(QtCore.QRect(150, 310, 71, 20))
        self.c_extend_send_16.setObjectName("c_extend_send_16")
        self.b_extend_send_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_17.setGeometry(QtCore.QRect(0, 330, 41, 20))
        self.b_extend_send_17.setObjectName("b_extend_send_17")
        self.e_extend_send_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_17.setGeometry(QtCore.QRect(40, 330, 101, 20))
        self.e_extend_send_17.setObjectName("e_extend_send_17")
        self.c_extend_send_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_17.setGeometry(QtCore.QRect(150, 330, 71, 20))
        self.c_extend_send_17.setObjectName("c_extend_send_17")
        self.b_extend_send_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_18.setGeometry(QtCore.QRect(0, 350, 41, 20))
        self.b_extend_send_18.setObjectName("b_extend_send_18")
        self.e_extend_send_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_18.setGeometry(QtCore.QRect(40, 350, 101, 20))
        self.e_extend_send_18.setObjectName("e_extend_send_18")
        self.c_extend_send_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_18.setGeometry(QtCore.QRect(150, 350, 71, 20))
        self.c_extend_send_18.setObjectName("c_extend_send_18")
        self.b_extend_send_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_19.setGeometry(QtCore.QRect(0, 370, 41, 20))
        self.b_extend_send_19.setObjectName("b_extend_send_19")
        self.e_extend_send_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_19.setGeometry(QtCore.QRect(40, 370, 101, 20))
        self.e_extend_send_19.setObjectName("e_extend_send_19")
        self.c_extend_send_19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_19.setGeometry(QtCore.QRect(150, 370, 71, 20))
        self.c_extend_send_19.setObjectName("c_extend_send_19")
        self.b_extend_send_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_20.setGeometry(QtCore.QRect(0, 390, 41, 20))
        self.b_extend_send_20.setObjectName("b_extend_send_20")
        self.e_extend_send_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_20.setGeometry(QtCore.QRect(40, 390, 101, 20))
        self.e_extend_send_20.setObjectName("e_extend_send_20")
        self.c_extend_send_20 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_20.setGeometry(QtCore.QRect(150, 390, 71, 20))
        self.c_extend_send_20.setObjectName("c_extend_send_20")
        self.b_extend_send_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_21.setGeometry(QtCore.QRect(0, 410, 41, 20))
        self.b_extend_send_21.setObjectName("b_extend_send_21")
        self.e_extend_send_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_21.setGeometry(QtCore.QRect(40, 410, 101, 20))
        self.e_extend_send_21.setObjectName("e_extend_send_21")
        self.c_extend_send_21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_21.setGeometry(QtCore.QRect(150, 410, 71, 20))
        self.c_extend_send_21.setObjectName("c_extend_send_21")
        self.b_extend_send_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.b_extend_send_22.setGeometry(QtCore.QRect(0, 430, 41, 20))
        self.b_extend_send_22.setObjectName("b_extend_send_22")
        self.e_extend_send_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.e_extend_send_22.setGeometry(QtCore.QRect(40, 430, 101, 20))
        self.e_extend_send_22.setObjectName("e_extend_send_22")
        self.c_extend_send_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.c_extend_send_22.setGeometry(QtCore.QRect(150, 430, 71, 20))
        self.c_extend_send_22.setObjectName("c_extend_send_22")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_2.addWidget(self.scrollArea_5)
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 3)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_7)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setMinimumSize(QtCore.QSize(100, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(100, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 116))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.c_hex_send = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c_hex_send.setGeometry(QtCore.QRect(0, 20, 71, 20))
        self.c_hex_send.setMaximumSize(QtCore.QSize(200, 16777215))
        self.c_hex_send.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.c_hex_send.setObjectName("c_hex_send")
        self.lcd_send_len = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcd_send_len.setGeometry(QtCore.QRect(30, 50, 71, 20))
        self.lcd_send_len.setDigitCount(8)
        self.lcd_send_len.setProperty("value", 0.0)
        self.lcd_send_len.setProperty("intValue", 0)
        self.lcd_send_len.setObjectName("lcd_send_len")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(0, 50, 54, 16))
        self.label.setObjectName("label")
        self.b_clear_send = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.b_clear_send.setGeometry(QtCore.QRect(10, 80, 81, 23))
        self.b_clear_send.setObjectName("b_clear_send")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.e_send = QtWidgets.QTextEdit(self.groupBox)
        self.e_send.setEnabled(True)
        self.e_send.setObjectName("e_send")
        self.horizontalLayout_3.addWidget(self.e_send)
        self.frame_8 = QtWidgets.QFrame(self.groupBox)
        self.frame_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.b_send = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_send.sizePolicy().hasHeightForWidth())
        self.b_send.setSizePolicy(sizePolicy)
        self.b_send.setMinimumSize(QtCore.QSize(0, 30))
        self.b_send.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.b_send.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_send.setAutoFillBackground(False)
        self.b_send.setObjectName("b_send")
        self.verticalLayout_7.addWidget(self.b_send)
        self.c_auto_send = QtWidgets.QCheckBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_auto_send.sizePolicy().hasHeightForWidth())
        self.c_auto_send.setSizePolicy(sizePolicy)
        self.c_auto_send.setMaximumSize(QtCore.QSize(80, 16777215))
        self.c_auto_send.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c_auto_send.setObjectName("c_auto_send")
        self.verticalLayout_7.addWidget(self.c_auto_send)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.e_auto_send_time = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.e_auto_send_time.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.e_auto_send_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e_auto_send_time.setDecimals(3)
        self.e_auto_send_time.setMinimum(0.001)
        self.e_auto_send_time.setSingleStep(0.1)
        self.e_auto_send_time.setProperty("value", 1.0)
        self.e_auto_send_time.setObjectName("e_auto_send_time")
        self.horizontalLayout_5.addWidget(self.e_auto_send_time)
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.e_debug_info = QtWidgets.QTextEdit(self.groupBox_6)
        self.e_debug_info.setObjectName("e_debug_info")
        self.verticalLayout_6.addWidget(self.e_debug_info)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_9.addWidget(self.frame_7)
        ToolSet.setCentralWidget(self.centralwidget)
        self.actionopen = QtWidgets.QAction(ToolSet)
        self.actionopen.setObjectName("actionopen")
        self.actionOpen = QtWidgets.QAction(ToolSet)
        self.actionOpen.setObjectName("actionOpen")
        self.action_Save = QtWidgets.QAction(ToolSet)
        self.action_Save.setObjectName("action_Save")
        self.label_2.setBuddy(self.serial_port)
        self.label_3.setBuddy(self.baudrate)
        self.label_5.setBuddy(self.e_tcp_port)
        self.label_4.setBuddy(self.e_ipaddr)

        self.retranslateUi(ToolSet)
        self.tool_cfg.setCurrentIndex(0)
        self.mode_manage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ToolSet)

    def retranslateUi(self, ToolSet):
        _translate = QtCore.QCoreApplication.translate
        ToolSet.setWindowTitle(_translate("ToolSet", "MainWindow"))
        self.groupBox_2.setTitle(_translate("ToolSet", "选项栏"))
        self.b_open.setText(_translate("ToolSet", "打开"))
        self.label_2.setText(_translate("ToolSet", "端口"))
        self.label_3.setText(_translate("ToolSet", "波特率"))
        self.tool_cfg.setItemText(self.tool_cfg.indexOf(self.serial_cfg), _translate("ToolSet", "串口配置"))
        self.label_5.setText(_translate("ToolSet", "端口"))
        self.label_4.setText(_translate("ToolSet", "IP"))
        self.b_connect.setText(_translate("ToolSet", "连接"))
        self.tool_cfg.setItemText(self.tool_cfg.indexOf(self.tcp_cfg), _translate("ToolSet", "TCP/IP配置"))
        self.b_status_control.setText(_translate("ToolSet", "连接"))
        self.label_7.setText(_translate("ToolSet", "接收"))
        self.b_clean_recv.setText(_translate("ToolSet", "清空"))
        self.label_9.setText(_translate("ToolSet", "字号"))
        self.c_hex_show.setText(_translate("ToolSet", "十六进制显示"))
        self.mode_manage.setTabText(self.mode_manage.indexOf(self.tab_serial), _translate("ToolSet", "数据面板"))
        self.groupBox_5.setTitle(_translate("ToolSet", "通道控制"))
        self.checkBox_2.setText(_translate("ToolSet", "CheckBox"))
        self.mode_manage.setTabText(self.mode_manage.indexOf(self.wearform), _translate("ToolSet", "示波器"))
        self.groupBox_3.setTitle(_translate("ToolSet", "快捷发送"))
        self.c_extend_send_1.setText(_translate("ToolSet", "1"))
        self.c_extend_cyclic_send.setText(_translate("ToolSet", "循环发送"))
        self.c_entend_enter.setText(_translate("ToolSet", "发送换行"))
        self.b_extend_send_all.setText(_translate("ToolSet", "发送按顺序"))
        self.c_all_exend_send.setText(_translate("ToolSet", "全选"))
        self.b_extend_send_1.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_2.setText(_translate("ToolSet", "2"))
        self.b_extend_send_2.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_3.setText(_translate("ToolSet", "3"))
        self.b_extend_send_3.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_4.setText(_translate("ToolSet", "4"))
        self.b_extend_send_4.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_5.setText(_translate("ToolSet", "5"))
        self.b_extend_send_5.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_6.setText(_translate("ToolSet", "6"))
        self.b_extend_send_6.setText(_translate("ToolSet", "发送"))
        self.b_extend_send_7.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_7.setText(_translate("ToolSet", "7"))
        self.b_extend_send_8.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_8.setText(_translate("ToolSet", "8"))
        self.b_extend_send_9.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_9.setText(_translate("ToolSet", "9"))
        self.b_extend_send_10.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_10.setText(_translate("ToolSet", "10"))
        self.b_extend_send_11.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_11.setText(_translate("ToolSet", "11"))
        self.b_extend_send_12.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_12.setText(_translate("ToolSet", "12"))
        self.b_extend_send_13.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_13.setText(_translate("ToolSet", "13"))
        self.b_extend_send_14.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_14.setText(_translate("ToolSet", "14"))
        self.b_extend_send_15.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_15.setText(_translate("ToolSet", "15"))
        self.b_extend_send_16.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_16.setText(_translate("ToolSet", "16"))
        self.b_extend_send_17.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_17.setText(_translate("ToolSet", "17"))
        self.b_extend_send_18.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_18.setText(_translate("ToolSet", "18"))
        self.b_extend_send_19.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_19.setText(_translate("ToolSet", "19"))
        self.b_extend_send_20.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_20.setText(_translate("ToolSet", "20"))
        self.b_extend_send_21.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_21.setText(_translate("ToolSet", "21"))
        self.b_extend_send_22.setText(_translate("ToolSet", "发送"))
        self.c_extend_send_22.setText(_translate("ToolSet", "22"))
        self.groupBox.setTitle(_translate("ToolSet", "发送区"))
        self.c_hex_send.setText(_translate("ToolSet", "十六进制"))
        self.label.setText(_translate("ToolSet", "发送"))
        self.b_clear_send.setText(_translate("ToolSet", "清空"))
        self.b_send.setText(_translate("ToolSet", "发送"))
        self.c_auto_send.setText(_translate("ToolSet", "自动发送"))
        self.label_8.setText(_translate("ToolSet", "S"))
        self.groupBox_6.setTitle(_translate("ToolSet", "调试窗口"))
        self.actionopen.setText(_translate("ToolSet", "&open"))
        self.actionopen.setToolTip(_translate("ToolSet", "<html><head/><body><p><span style=\" font-weight:600;\">open</span></p></body></html>"))
        self.actionOpen.setText(_translate("ToolSet", "Open"))
        self.action_Save.setText(_translate("ToolSet", "&Save"))
from pyqtgraph import PlotWidget
